# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: clickhouse-flamegraph
before:
  hooks:
    - rm -rf ./dist/
    - go mod tidy
builds:
  - id: clickhouse-flamegraph
    main: main.go
    binary: clickhouse-flamegraph
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256
archives:
  - id: clickhouse-flamegraph
    wrap_in_directory: "false"
    files:
      - "README.md"
      - "LICENSE"
      - "flamegraph.pl"
nfpms:
  - id: clickhouse-flamegraph
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    homepage: https://github.com/Slach/clickhouse-flamegraph
    maintainer: Slach <bloodjazman@gmail.com>
    description: command line utility for visualizing clickhouse system.trace_log as flamegraph
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - perl
    bindir: /usr/bin
    epoch: 1
    contents:
      - src: "flamegraph.pl"
        dst: "/usr/bin/flamegraph.pl"
      - dst: /var/log/clickhouse-flamegraph
        type: dir
release:
  github:
    owner: Slach
    name: clickhouse-flamegraph
  prerelease: auto
changelog:
  use: git
